parameters:
    binder_page.dirname: pages
    binder_page.path: "%kernel.root_dir%/Resources/views/%binder_page.dirname%"

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Binder\PageBundle\Controller\PageController:
        public: true

    Binder\PageBundle\Service\PageDirectory:
        arguments:
            $path: "%binder_page.path%"

    Binder\PageBundle\Service\TemplateLocator: ~

    Binder\PageBundle\Service\AutoMenu: ~

    Binder\PageBundle\Twig\PageExtension: ~

